### ISSUE TITLE
Unsupported apps should be notated or removed

### ISSUE THREAD

**Issue by alexthemitchell** [GrinnellAppDev/Website#7]
Both #grinnwell and FaceTag are no longer supported and either should be placed in a group below the supported apps (and marked as Unsupported) or removed from the page altogether. 
<img width="1293" alt="screen shot 2016-07-16 at 7 32 31 pm" src="https://cloud.githubusercontent.com/assets/5687158/16898370/12d4cf52-4b8c-11e6-9c12-54e170f4e6ea.png">

**Comment by sarahtrop** [comment]
Done, removed unsupported apps
