### ISSUE TITLE
Apply Page: Job Description Unreadable

### ISSUE THREAD

**Issue by alexthemitchell** [GrinnellAppDev/Website#8]
Dark text on Dark background is hard to read.

http://appdev.grinnell.edu/apply.php
<img width="1440" alt="screen shot 2016-08-14 at 11 58 08 am" src="https://cloud.githubusercontent.com/assets/5687158/17651200/ca4448ca-6216-11e6-8070-3c9272be5cc7.png">

**Comment by sarahtrop** [comment]
Fixed
